### ISSUE TITLE
Logging: Sometimes produce invalid csv files

### ISSUE THREAD

**Issue by bastianilso** [med-material/bci-PAM-game#4]
Some csv files cant get imported because they are missing some cell values in certain places and I have to fill those values manually myself with 'NULL'. It's usually the last 3 or last 6 cells at the end of the 2 last rows in the csv files. see attached example ("GameStopped" event).

![image](https://user-images.githubusercontent.com/3967945/125926292-4780e342-169d-4cd7-b735-7f9fa9311602.png)

Also, there seems to be 2 GameStopped events and not just one.
[log2021-07-01 10-15-19.2554Game.csv](https://github.com/med-material/bci-PAM-game/files/6829576/log2021-07-01.10-15-19.2554Game.csv)

**Comment by ingebronx** [comment]
Should hopefully be fixed now.
