### ISSUE TITLE
Augmented Success: Condition always leads to worse performance

### ISSUE THREAD

**Issue by bastianilso** [med-material/bci-PAM-game#6]
Augmented Success is leading to worse performance in our experiments. Looking into the code, it seems that whenever it is not possible to move a fish up by 2 lanes, the game defaults to rejection. This happens relatively often and causes the PAM rate and acceptance rate of any AS condition to be lower than it is supposed to.

**Comment by hendrikknoche** [comment]
yes, this seems to be conceptual mistake. 
Ideally, we would use the urn and pull a success from it (ie. not allowing for AS when fish are in lane 1) and put the AS back in again. 
I guess this would also mean that we don't want many if any fish to spawn in lane 1.

**Comment by bastianilso** [comment]
fixed in f4616c8ba4656e31606af1932fbe970e76230d05
